### ISSUE TITLE
NoClassDefFoundError on plugin startup

### ISSUE THREAD

**Issue by Yiixez** [Odalita-Developments/OdalitaMenus#20]
Im not sure why i get this error and how i could fix it, i do have ProtocolLib but according to your spigot page it is not required. So i am not sure why i am getting this error.

```
[15:38:39 ERROR]: Error occurred while enabling cosmetics v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
        at nl.odalitadevelopments.menus.providers.ProvidersContainer.<init>(ProvidersContainer.java:34) ~[cosmetics-1.0.jar:?]
        at nl.odalitadevelopments.menus.OdalitaMenusImpl.<init>(OdalitaMenusImpl.java:110) ~[cosmetics-1.0.jar:?]
        at nl.odalitadevelopments.menus.OdalitaMenusImpl.createInstance(OdalitaMenusImpl.java:59) ~[cosmetics-1.0.jar:?]
        at nl.odalitadevelopments.menus.OdalitaMenus.createInstance(OdalitaMenus.java:27) ~[cosmetics-1.0.jar:?]
        at gg.stray.cosmetics.Cosmetics.onEnable(Cosmetics.java:33) ~[cosmetics-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Yiixez** [comment]
![image](https://github.com/user-attachments/assets/3b80cb7d-1482-49c0-a3b0-20c662a60595)

**Comment by Yiixez** [comment]
i use ProtocolLib v5.2, soft-depend and depend both do not change the outcome.

**Comment by ItzKiwiSap** [comment]
I see you closed it, what fixed it?

**Comment by Yiixez** [comment]
i created the project with Manifest enabled, recreating it with it disabled resolved the issue for some reason.
![image](https://github.com/user-attachments/assets/ee9d40a6-93e8-4b11-8b50-2c0cebbc3ad5)

**Comment by ItzKiwiSap** [comment]
Interesting, thanks for responding!
